### PR TITLE
fix fallback to default demo model

### LINKED ISSUE #57: If the default model is not found, the application crashes at startup
1. Change the default model to something other than the default duck
2. Delete/move the new model
3. Open the application again
4. Observe the crash

### PR DESCRIPTION
**Pull request by Zutatensuppe**
fixes #57

- removes preload of duck scene (not required, right? usually ppl will use their own models anyway)
- when the model cant be loaded (only file missing check is currently in place) then the default model (duck) is loaded
- removed overwriting of the config with the duck scene, as there is a fallback in place anyway and if the removed file gets moved back, it should still be the one that is loaded by default

### CODE REVIEW

**Comment by you-win** [comment]
These changes make sense. Is it ready to merge?

**Comment by Zutatensuppe** [comment]
yup, should be ready, i dont know if of the prs can be merged without checking for merge conflicts, but other than that they should be ready ^^

**Comment by Zutatensuppe** [comment]
i ll fix the conflicts =)

**Comment by Zutatensuppe** [comment]
its really strange, i had to restore the hack (?) with setting vrm_meta even though it should be there, see https://github.com/you-win/openseeface-gd/pull/62/commits/d26a86c416131ac5827cad50a9f55eabc0e82663

but now it should be fine to merge for now

**Comment by you-win** [comment]
> i had to restore the hack (?) with setting vrm_meta

I think it's because the script is being swapped at runtime. Initially, `vrm_loader` loads the model in with a `vrm_toplevel.gd` script. We then change the script to `vrm_model.gd` and lose the `vrm_meta` variable, so we need to store and set the `vrm_meta` value again.

This could be worked around by nesting the loaded vrm model inside of another node, but I think the only benefit would be access to the various [`VRMUtil`](https://github.com/you-win/openseeface-gd/blob/master/addons/vrm/vrm_toplevel.gd) functions, which might actually be necessary now that I'm thinking about it. 🤔

Anyways, thanks for the PR!

**Pull request merged**
