### PR TITLE
add Logger class

### PR DESCRIPTION
**Pull request by Zutatensuppe**
added logger class in hopes to be able to stub it later in unit tests (because in the logger there is an `assert` statement, which makes tests fail if part of the code wants to be tested that runs into it)

### CODE REVIEW

**Comment by you-win** [comment]
Is this ready to merge? And should this be merged before #62 ?

**Comment by Zutatensuppe** [comment]
yea it should be ready, i think order doesnt matter, i ll just fix the conflicts if any arise :+1:

**Comment by you-win** [comment]
A wild merge conflict has appeared

**Comment by Zutatensuppe** [comment]
fixed conflicts ^_^

**Comment by you-win** [comment]
Thanks for the PR!

**Pull request merged**
